# Generated by Django 4.1.1 on 2022-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=32)),
                ('modelo', models.CharField(max_length=32)),
                ('ano', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comentario', models.CharField(max_length=128)),
            ],
        ),
    ]
